const root=document.getElementById("app");
const tokenKey="ca_token";
let state={page:"dashboard",products:[],selected:null,history:[]};

const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function auth(){return localStorage.getItem(tokenKey)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}), "Content-Type":"application/json","Authorization":`Bearer ${auth()}`}; const r=await fetch(url,opt); const d=await r.json().catch(()=>({})); if(!r.ok) throw Error(d.error||"Erro"); return d}
function money(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function pill(s){let c=s==="VENDENDO"?"green":s==="PUBLICADO"?"green":s==="VIDEO_PRONTO"?"orange":s==="PROMPT_PRONTO"?"purple":s==="PAUSADO"?"red":"".trim(); return `<span class="pill ${c}">${esc(s.replaceAll("_"," "))}</span>`}

async function load(){state.products=await api("/api/products"); render()}
function nav(){return `<aside class="side"><div class="logo">S</div><div class="brand">SHOPEE AFILIADO<br><span class="muted">Central de Operações</span></div>
<button class="nav ${state.page==="dashboard"?"active":""}" onclick="go('dashboard')">⌂ Dashboard</button>
<button class="nav ${state.page==="products"?"active":""}" onclick="go('products')">◇ Produtos</button>
<button class="nav" onclick="alert('Central de IA entra na próxima etapa de integração.')">🤖 Central de IA</button>
<button class="nav" onclick="alert('Central de Mídia entra na próxima etapa.')">▶ Vídeos</button>
<button class="nav" onclick="alert('Publicações entram na próxima etapa.')">□ Publicações</button>
<button class="nav" onclick="alert('Métricas entram na próxima etapa.')">▥ Métricas</button>
<button class="nav" onclick="logout()" style="margin-top:30px">↪ Sair</button></aside>`}
function mobile(){return `<div class="mobilebar"><button onclick="go('dashboard')">⌂<br>Início</button><button onclick="go('products')">◇<br>Produtos</button><button onclick="newProduct()">＋<br>Novo</button><button onclick="alert('IA entra na próxima etapa.')">🤖<br>IA</button></div>`}
function shell(content,title,sub){return `<div class="layout">${nav()}<main class="content"><div class="top"><div><div class="title">${title}</div><div class="muted">${sub}</div></div><button class="primary" onclick="newProduct()">＋ Adicionar produto</button></div>${content}</main>${mobile()}</div>`}
function render(){ if(!auth()){renderLogin();return} state.page==="products"?renderProducts():renderDashboard() }
function renderLogin(){root.innerHTML=`<div class="login"><div class="card"><div class="logo">S</div><h2 class="center">SHOPEE AFILIADO</h2><p class="center muted">Central de Operações</p><label>E-mail</label><input id="email" value="admin@local"><label>Senha</label><input id="pass" type="password" value="1234"><button class="primary" style="width:100%;margin-top:20px" onclick="login()">ENTRAR</button><p class="center muted" style="font-size:12px;margin-top:18px">Acesso inicial: admin@local / 1234</p></div></div>`}
async function login(){try{const d=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:document.getElementById("email").value,password:document.getElementById("pass").value})}).then(r=>r.json());if(!d.token)throw Error(d.error);localStorage.setItem(tokenKey,d.token);await load()}catch(e){alert(e.message)}}
function logout(){localStorage.removeItem(tokenKey);render()}
function go(p){state.page=p;render()}
function renderDashboard(){const n=state.products.length, com=state.products.reduce((a,p)=>a+Number(p.commission||0),0);const content=`<section class="stats"><div class="stat"><small>🛍 PRODUTOS</small><b>${n}</b></div><div class="stat"><small>🎬 VÍDEOS</small><b>0</b></div><div class="stat"><small>📢 PUBLICADOS</small><b>0</b></div><div class="stat"><small>🖱 CLIQUES</small><b>0</b></div><div class="stat"><small>💰 COMISSÃO</small><b>${money(com)}</b></div></section><section class="panel"><div class="toolbar"><h3>Meus produtos</h3><input class="search" placeholder="🔎 Pesquisar produto..." oninput="filterProducts(this.value)"></div><div id="table"></div></section>`;root.innerHTML=shell(content,"Dashboard","Controle central dos seus produtos e links.");fillTable(state.products)}
function renderProducts(){const content=`<section class="panel" style="margin-top:20px"><div class="toolbar"><div><h3 style="margin:0">Central de Links</h3><span class="muted">Todos os produtos e links da operação</span></div><input class="search" placeholder="🔎 Pesquisar produto..." oninput="filterProducts(this.value)"></div><div id="table"></div></section>`;root.innerHTML=shell(content,"Produtos","Sua biblioteca permanente de produtos e links.");fillTable(state.products)}
function fillTable(rows){const el=document.getElementById("table");if(!rows.length){el.innerHTML=`<div class="center muted" style="padding:45px">Nenhum produto cadastrado.<br><br><button class="primary" onclick="newProduct()">＋ Adicionar primeiro produto</button></div>`;return}el.innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Produto</th><th>Categoria</th><th>Status</th><th>Preço</th><th>Comissão</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.category)}</td><td>${pill(p.status)}</td><td>${money(p.price)}</td><td>${money(p.commission)}</td><td><button onclick="openProduct(${p.id})">Abrir</button></td></tr>`).join("")}</tbody></table></div>`}
function filterProducts(q){q=q.toLowerCase();fillTable(state.products.filter(p=>(p.name+" "+p.category+" "+p.status).toLowerCase().includes(q)))}
function newProduct(){openForm()}
function openForm(p={}){root.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modalbox"><h2>${p.id?"Editar":"Novo"} produto</h2><div class="grid2"><div><label>Nome</label><input id="f_name" value="${esc(p.name)}"></div><div><label>Categoria</label><select id="f_category">${["Casa","Tecnologia","Eletrônicos","Moda","Beleza","Fitness","Automotivo","Ferramentas","Eletrodomésticos","Outros"].map(x=>`<option ${x===(p.category||"Outros")?"selected":""}>${x}</option>`).join("")}</select></div><div><label>Preço</label><input id="f_price" inputmode="decimal" value="${p.price||""}"></div><div><label>Comissão</label><input id="f_commission" inputmode="decimal" value="${p.commission||""}"></div><div><label>Link original</label><input id="f_original" value="${esc(p.original_link)}"></div><div><label>Link de afiliado</label><input id="f_affiliate" value="${esc(p.affiliate_link)}"></div><div style="grid-column:1/-1"><label>Status</label><select id="f_status">${["NOVO","EM_PRODUCAO","PROMPT_PRONTO","VIDEO_PRONTO","PUBLICADO","VENDENDO","PRODUTO_VENCEDOR","PAUSADO"].map(x=>`<option ${x===(p.status||"NOVO")?"selected":""}>${x}</option>`).join("")}</select></div><div style="grid-column:1/-1"><label>Observações</label><textarea id="f_notes" rows="4">${esc(p.notes)}</textarea></div></div><div class="actions"><button onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveProduct(${p.id||0})">SALVAR</button></div></div></div>`)}
function closeModal(){document.getElementById("modal")?.remove()}
async function saveProduct(id){const data={name:f("f_name"),category:f("f_category"),price:f("f_price"),commission:f("f_commission"),original_link:f("f_original"),affiliate_link:f("f_affiliate"),status:f("f_status"),notes:f("f_notes")};try{if(id)await api("/api/products/"+id,{method:"PATCH",body:JSON.stringify(data)});else await api("/api/products",{method:"POST",body:JSON.stringify(data)});closeModal();await load()}catch(e){alert(e.message)}}
function f(id){return document.getElementById(id).value}
async function openProduct(id){const p=state.products.find(x=>x.id===id);const hist=await api("/api/products/"+id+"/history");root.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modalbox"><div class="top"><div><h2>${esc(p.name)}</h2><div class="muted">PROD-${String(p.id).padStart(4,"0")} • ${esc(p.category)} • ${pill(p.status)}</div></div><button onclick="closeModal()">✕</button></div><div class="grid2" style="margin-top:20px"><div class="panel"><small class="muted">PREÇO</small><h3>${money(p.price)}</h3></div><div class="panel"><small class="muted">COMISSÃO</small><h3>${money(p.commission)}</h3></div></div><div class="panel" style="margin-top:12px"><b>🔗 Links</b><p><small>Original</small><br>${esc(p.original_link||"—")}</p><p><small>Afiliado</small><br>${esc(p.affiliate_link||"—")}</p></div><div class="panel" style="margin-top:12px"><b>🧠 Próxima ação</b><p>${nextAction(p)}</p></div><div class="panel" style="margin-top:12px"><b>🕒 Histórico</b>${hist.map(h=>`<p class="muted">${new Date(h.created_at).toLocaleString("pt-BR")} — ${esc(h.event)}</p>`).join("")}</div><div class="actions"><button onclick="closeModal()">Fechar</button><button class="primary" onclick="closeModal();openForm(state.products.find(x=>x.id===${id}))">Editar produto</button></div></div></div>`)}
function nextAction(p){if(!p.affiliate_link)return"Adicionar o link de afiliado";if(p.status==="NOVO")return"Colocar produto em produção";if(p.status==="EM_PRODUCAO")return"Gerar prompt";if(p.status==="PROMPT_PRONTO")return"Produzir vídeo";if(p.status==="VIDEO_PRONTO")return"Publicar vídeo";if(p.status==="PUBLICADO")return"Acompanhar cliques e vendas";if(p.status==="VENDENDO")return"Criar novos vídeos para escalar";return"Revisar produto"}
render();